### ISSUE TITLE
Feature Request: filename check before upgrade

### ISSUE THREAD

**Issue by jekader** [pixelit-project/PixelIt.WebUI#58]
Bricked one of my boards by accident since I had too many PixelIt tabs open at the same time so here's a feature request:

Firmware files have predictable names  like `firmware_<version>_<target>.bin` and both the version and build target are known to the UI.

It would be nice if the UI can verify that the filename provided for firmware upgrade has a version not lower than the existing one and a matching build target. If the file has an unexpected name - print out a warning to the user who can then decide whether to proceed or abort the upgrade.

**Comment by o0shojo0o** [comment]
The WebUI could even check the version in the configuration file. 
Once I have some time, I will take a closer look at it.

**Comment by o0shojo0o** [comment]
This is how it is implemented, the check is made via the filename. if something cannot be determined, it is also checked. 

![image](https://github.com/user-attachments/assets/f2093230-d1fc-4a3e-9905-369803ada65e)

**Comment by jekader** [comment]
Thanks, looks awesome!
